In [4]:
import numpy as np

array = np.array([2,1,4])

print(array.dtype)


int64


In [2]:
array_2 = np.array([3,4,5], dtype=np.float)

print(array_2.dtype)

float64


In [8]:
a = np.array([[3,5,6], [8,9,1]])
print(a)

[[3 5 6]
 [8 9 1]]


In [13]:
zero_array = np.zeros((3, 4))
print(zero_array)

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


In [14]:
one_array = np.ones((3, 5), dtype=np.int)
print(one_array)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [15]:
empty_array = np.empty((2, 1))
print(empty_array)

[[ 0.        ]
 [-2.00000012]]


In [16]:
print(np.arange(10, 18, 2))

[10 12 14 16]


In [24]:
print(np.arange(12).reshape(3,4))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [19]:
print(np.linspace(1, 10, 20))

[  1.           1.47368421   1.94736842   2.42105263   2.89473684
   3.36842105   3.84210526   4.31578947   4.78947368   5.26315789
   5.73684211   6.21052632   6.68421053   7.15789474   7.63157895
   8.10526316   8.57894737   9.05263158   9.52631579  10.        ]


In [35]:
print(np.linspace(1, 10, 6).reshape(2, 3))

[[  1.    2.8   4.6]
 [  6.4   8.2  10. ]]
