In [2]:
import numpy as np

a = np.array([3, 4, 100])
b = np.arange(3)
print('a:', a)
print('b:', b)

a: [  3   4 100]
b: [0 1 2]


In [4]:
print(a - b)

[ 3  3 98]


In [9]:
print(a**2)

[    9    16 10000]


In [11]:
print(b<2)

[ True  True False]


In [12]:
print(b==2)

[False False  True]


In [6]:
c = np.array([[1,1],[0,1]])
d = np.arange(4).reshape(2,2)

print(c*d)

[[0 1]
 [0 3]]


In [7]:
print(np.dot(c, d))    # 矩陣乘法

[[2 4]
 [2 3]]


In [8]:
print(c.dot(d))    # 矩陣乘法

[[2 4]
 [2 3]]


In [18]:
random_array = np.random.random((2,4))     # 創建值 0 ~ 1 的陣列
print(random_array)

# axis可設定為 0 或 1，當 axis 的值為 0 時，以行為基準，反之，當 axis 的值為 1 時，以列為基礎
print('sum:', np.sum(random_array, axis=1))    
print('max:', np.min(random_array, axis=0))
print('min:', np.max(random_array, axis=1))

[[ 0.49651734  0.93295404  0.26110219  0.54859516]
 [ 0.65768968  0.1712239   0.15369895  0.51886555]]
sum: [ 2.23916874  1.50147807]
max: [ 0.49651734  0.1712239   0.15369895  0.51886555]
min: [ 0.93295404  0.65768968]
