In [4]:
import numpy as np

A = np.arange(2, 14).reshape(3,4)

print(np.argmin(A))    # 最小值的 index
print(np.argmax(A))    # 最大值的 index
print(np.mean(A))      # 整個陣列的平均值   
print(A)

0
11
7.5
[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]


In [5]:
print(A.mean())

7.5


In [8]:
print(np.average(A))

7.5


In [9]:
print(np.median(A))    # 陣列的中位數

7.5


In [10]:
print(np.cumsum(A))    # 陣列累加的過程

[ 2  5  9 14 20 27 35 44 54 65 77 90]


In [12]:
print(np.diff(A))    # 陣列中，每兩個數之間的差

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [13]:
print(np.nonzero(A))

(array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2], dtype=int64), array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3], dtype=int64))


In [15]:
B = np.arange(14, 2, -1).reshape(3, 4)
print(np.sort(B))    # 逐行排列

[[11 12 13 14]
 [ 7  8  9 10]
 [ 3  4  5  6]]


In [19]:
print(np.transpose(A))    # 行列互換
print((A.T).dot(A))

[[ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]
 [ 5  9 13]]
[[140 158 176 194]
 [158 179 200 221]
 [176 200 224 248]
 [194 221 248 275]]


In [20]:
print(np.clip(A, 5, 9))    # 陣列中的數字小於5，則置換成 5，而陣列中的數字大於 9，則置換成 9

[[5 5 5 5]
 [6 7 8 9]
 [9 9 9 9]]
