In [1]:
import numpy as np 

A = np.arange(3, 15)
print(A)

[ 3  4  5  6  7  8  9 10 11 12 13 14]


In [2]:
print(A[3])

6


In [6]:
A = np.arange(3, 15).reshape(3, 4)
print(A)
print(A[2])
print(A[1][1])
print(A[1, 1])    # 與 A[1][1] 一樣的功能

[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]
[11 12 13 14]
8
8


In [7]:
print(A[2,:])    # 第 2 列的所有數

[11 12 13 14]


In [8]:
print(A[:, 1])    # 第 1 行的所有數

[ 4  8 12]


In [10]:
print(A[1, 1:3])    # 第 1 列中索引值為 1 ~ 2 的所有數

[8 9]


In [11]:
for row in A:
    print(row)

[3 4 5 6]
[ 7  8  9 10]
[11 12 13 14]


In [12]:
# 將陣列轉至以後，可以直接迭代陣列中的行

for column in A.T:
    print(column)

[ 3  7 11]
[ 4  8 12]
[ 5  9 13]
[ 6 10 14]


In [17]:
print(A.flatten())

# 將陣列中的值一個一個迭代
for item in A.flat:
    print(item)

[ 3  4  5  6  7  8  9 10 11 12 13 14]
3
4
5
6
7
8
9
10
11
12
13
14
