In [20]:
import numpy as np

A = np.array([1,1,1])
B = np.array([2,2,2])

C = np.vstack((A, B))    # vertical stack
print(A.shape, C.shape)

(3,) (2, 3)


In [21]:
D = np.hstack((A, B))   # horizontal stack
print(D)
print(D.shape)

[1 1 1 2 2 2]
(6,)


In [22]:
print(A.reshape(3,1))

[[1]
 [1]
 [1]]


In [23]:
print(A[:, np.newaxis].shape)
print(A[:, np.newaxis])

(3, 1)
[[1]
 [1]
 [1]]


In [34]:
A = np.array([1,1,1])[:, np.newaxis]
B = np.array([2,2,2])[:, np.newaxis]
print(A)
print('-----')
print(B)

[[1]
 [1]
 [1]]
-----
[[2]
 [2]
 [2]]


In [32]:
print(np.concatenate((A, B)))

[[1]
 [1]
 [1]
 [2]
 [2]
 [2]]


In [30]:
C = np.concatenate((A, B), axis=1)
print(C)


[[1 2]
 [1 2]
 [1 2]]
