In [2]:
import numpy as np

a = np.arange(4)
print(a)

[0 1 2 3]


In [4]:
b = a
c = a
d = b

In [5]:
a[0] = 4
print(a)

[4 1 2 3]


In [6]:
b

array([4, 1, 2, 3])

In [7]:
c

array([4, 1, 2, 3])

In [8]:
d

array([4, 1, 2, 3])

In [9]:
print(b is a)

True


In [10]:
d[1:3] = [22, 33]
d

array([ 4, 22, 33,  3])

In [11]:
a

array([ 4, 22, 33,  3])

In [12]:
b = a.copy()    # deep copy
b

array([ 4, 22, 33,  3])

In [13]:
a[3] = 44
a

array([ 4, 22, 33, 44])

In [14]:
b

array([ 4, 22, 33,  3])